# Copyright (c) 2026, Matthew Richardson
# (https://orcid.org/0009-0001-0977-2029).
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

._prefix_for_tag_urls as $tag_prefix | [
	"<!DOCTYPE\nhtml>",
	"<html\nclass=h-feed\nlang=en>",
	"<meta\ncharset=utf-8>",
	"<title>",
	.title,
	"</title>",
	"<link\nrel=stylesheet\nhref=./shared-style.css>",
	"<link\nrel=stylesheet\nhref=./column-style.css>",
	"<link\nrel=icon\nhref=",
	.icon,
	">",
	"<meta\nname=color-scheme\ncontent='dark light'>",
	"<meta\nname=description\ncontent='",
	.description,
	"'>",
	"<meta\nname=format-detection\ncontent='telephone=no'>",
	"<meta\nname=viewport\ncontent='width=device-width'>",
	"<header\nid=shared_top>",
	"<a\nhref=./>",
	"<img\nalt='Heart-shaped tromino icon.'\nsrc=./icons/♥.svg\nheight=40\nwidth=40>",
	"</a>",
	"<a\nhref=./mf2.html>blog</a>",
	"<span>❦</span>",
	"<a\nhref=./sitemap.html>sitemap</a>",
	"</header><hgroup>",
	"<h1\nclass='p-name site-title'>",
	"<a\nrel=bookmark\nhref=",
	.home_page_url,
	"\nclass=u-url>",
	.title,
	"</a></h1><p>",
	"<time\nclass=dt-updated>",
	._atom_elements.updated,
	"</time></hgroup>",
	"<p\nclass=p-summary>",
	.description,
	(.items | length as $len | to_entries[] | [
		"<article\nid='",
		$len - .key,
		"'\nclass=h-entry>",
		"<hgroup>",
		"<h2\nclass='entry-title p-name'>",
		"<a\nrel=bookmark\nhref=",
		.value.url,
		"\nclass=u-url>",
		.value.title,
		"</a></h2><p>",
		"<time\nclass=dt-published>",
		.value.date_published,
		"</time></hgroup>",
		"<div\nclass=e-content>",
		.value.content_html,
		"</div><footer><small>",
		"<samp\nclass=u-uid>",
		.value.id,
		"</samp> | Updated <time\nclass=dt-updated>",
		.value.date_modified,
		"</time></small>",
		"<p>Tags: ",
		([.value.tags[] | [
			"<a\nrel='category tag'\nhref=",
			$tag_prefix,
			.,
			"\nclass=p-category>",
			.,
			"</a>, "
		]] | flatten | join("")[:-2]),
		"</footer></article>"
	])
] | flatten | join("")
